name: smartscape
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1


environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  get: ^4.6.6
  get_storage: ^2.1.1
  package_info_plus: ^8.0.2
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  flutter_liquid_swipe: ^0.0.1
  cupertino_tabbar: ^2.0.0
  carousel_slider: ^5.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1





  # Firebase
  firebase_core: ^3.6.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  weather: ^3.1.1
  air_quality: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  csv: ^6.0.0
  path_provider: ^2.1.5
  table_calendar: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/animations/
    - assets/images/on_boarding_screen/
    - assets/images/email_verification/
    - assets/images/home_icons/
    - assets/images/events/
    - assets/images/ad_banner/
    - assets/logo/
    - assets/videos/
    - assets/icons/
    - assets/data/acres_price.csv
