// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr__oeMn9AER7WMT1BsCZ7f2X-e6pyKjA',
    appId: '1:598563023453:web:523bb4b5e1184649a0bbb4',
    messagingSenderId: '598563023453',
    projectId: 'smartscapeog',
    authDomain: 'smartscapeog.firebaseapp.com',
    storageBucket: 'smartscapeog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEVRH3caO4cOs-YVFMTpfnHb3Q4AljOE',
    appId: '1:598563023453:android:d86323eb685411d2a0bbb4',
    messagingSenderId: '598563023453',
    projectId: 'smartscapeog',
    storageBucket: 'smartscapeog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTgyIjIyGXlGdvBkUhn9MMX_IGO7tKiuc',
    appId: '1:598563023453:ios:ecd871118ec3f66aa0bbb4',
    messagingSenderId: '598563023453',
    projectId: 'smartscapeog',
    storageBucket: 'smartscapeog.firebasestorage.app',
    androidClientId: '598563023453-q9oicf8cbkjjl3fn3t3mo1622gnfps8u.apps.googleusercontent.com',
    iosClientId: '598563023453-ob0sdk2dphi7tn0khvvhk1doqt606351.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartscape',
  );

}